<?php 
  $helper = $this->helper('Earthsquared\Customize\Helper\Data');
  $websiteid = $helper->getWebsiteId();
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $customerSession = $objectManager->create('Magento\Customer\Model\Session');
  /* @var \Magento\Wishlist\Block\Link $block */
?>
  <?php if($websiteid == 1) { ?>
    <li class="wishtop" data-bind="scope: 'wishlist'"><a href="javascript:;">
      <img src="<?php echo $this->getUrl('pub/media/icons').'bookmark.png' ?>"  alt="Saved For Later" />
      <?php if($customerSession->isLoggedIn()){ ?>
      <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter" class="counter qty"></span>
      <!-- /ko -->
    <?php } ?>
    </a>
  </li>
  <?php } else { ?>
	 <li class="wishtop" data-bind="scope: 'wishlist'"><a href="javascript:;"><img src="<?php echo $this->getUrl('pub/media/icons').'heart.png' ?>" alt="Wishlist" />
    <?php if($customerSession->isLoggedIn()){ ?>
      <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter" class="counter qty"></span>
      <!-- /ko -->
      <!--<span data-bind="text: wishlist().items.length" class="counter qty"></span>-->
    <?php } ?></a>
  </li>
  <?php } ?>  
  <?php
  if($customerSession->isLoggedIn()){
		echo $this->getLayout()->createBlock("Magento\Wishlist\Block\Customer\Sidebar")->setTemplate("Magento_Wishlist::wishlisttopsidebar.phtml")->toHtml();
  }
  ?>
