<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Sidebar $block */
?>
<?php
$wishlistHelper = $this->helper(\Magento\Wishlist\Helper\Data::class);
?>
<?php if ($wishlistHelper->isAllow()) : ?>
    <div class="block block-wishlist topwishlistitems" data-bind="scope: 'wishlist'" style="display:none">
        <div class="block-title">
            <strong role="heading" aria-level="2"><?php echo __("Wish List") ?></strong>
            <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter" class="counter"></span>
            <!-- /ko -->
        </div>
        <div class="block-content">            
            <!-- ko if: wishlist().counter -->
                <ol class="product-items no-display" id="wishlist-sidebar" data-bind="foreach: wishlist().items, css: {'no-display': null}">
                    <li class="product-item">
                        <div class="product-item-info">
                            <a class="product-item-photo" data-bind="attr: { href: product_url, title: product_name }">
                                <!-- ko template: {name: $data.image.template, data: $data.image} --><!-- /ko -->
                            </a>
                            <div class="product-item-details">
                                <strong class="product-item-name">
                                    <a data-bind="attr: { href: product_url }" class="product-item-link">
                                        <span data-bind="html: product_name"></span>
                                    </a>
                                </strong>
                                <div>
                                    <!-- ko if: product_has_required_options && attribute-->
                                    <label style="font-weight: normal; color: #616161;font-family: Futura Bk BT;font-size: 12px;"><?= $block->escapeHtml(__('Colour:')) ?></label>
                                    <span style="font-weight: normal; color: #616161;font-family: Futura Bk BT;font-size: 12px;" data-bind="html: attribute"></span>
                                    <!-- /ko -->
                                </div>
                            </div>
                            <div class="price-addto">
                                <div data-bind="html: product_price"></div>
                                <div class="product-item-actions">
                                    <!-- ko if: product_is_saleable_and_visible -->
                                    <div class="actions-primary">
                                        <!-- ko if: product_has_required_options -->
                                        <a href="#" data-bind="attr: {'data-post': add_to_cart_params}" class="action tocart primary"><span><?= $block->escapeHtml(__('Move to Bag')) ?></span></a>
                                        <!-- /ko -->
                                        <!-- ko ifnot: product_has_required_options -->
                                            <button type="button" class="action tocart primary" data-bind="attr: {'data-post': add_to_cart_params}"><span><?= $block->escapeHtml(__('Move to Bag')) ?></span></button>
                                        <!-- /ko -->
                                    </div>
                                    <!-- /ko -->
                                    <div class="actions-secondary">
                                        <a href="#"  data-bind="attr: {'data-post': delete_item_params}"
                                           title="<?= $block->escapeHtmlAttr(__('Remove This Item')) ?>"
                                           class="btn-remove action delete">
                                            <span><?= $block->escapeHtml(__('Remove This Item')) ?></span>
                                        </a>
                                    </div>
                                </div>
                                </div>                            
                        </div>
                    </li>
                </ol>
                <div class="wishlist-total"> <!-- ko if: wishlist().subtotal -->
                    <div class="wishlist-title"><?= $block->escapeHtmlAttr(__('Subtotal')) ?></div>
                    <div class="wishlist-subtotal"><span data-bind="text: wishlist().subtotal" class="subtotal"></span></div>
            <!-- /ko --></div>
                <div class="actions-toolbar no-display" data-bind="css: {'no-display': null}">
                    <div class="primary">
                        <a class="action details"
                           href="<?= $block->escapeUrl($this->helper(\Magento\Wishlist\Helper\Data::class)->getListUrl()) ?>"
                           title="<?= $block->escapeHtmlAttr(__('View all items')) ?>"><span><?= $block->escapeHtml(__('View all items')) ?></span></a>
                    </div>
                </div>
            <!-- /ko -->
            <!-- ko ifnot: wishlist().counter -->
                <div class="empty"><?= $block->escapeHtml(__('You have no items in your wish list.')) ?></div>
            <!-- /ko -->
        </div>
    </div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }
</script>
<?php endif ?>