<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\History $block */
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>

    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
	<?php else : ?>
		<div class="message info empty"><span><?= $block->escapeHtml(__('You have placed no orders.')) ?></span></div>
	<?php endif ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <?php /*<th scope="col" class="col shipping"><?= $block->escapeHtml(__('Ship To')) ?></th> */?>
                    <th scope="col" class="col items"><?= $block->escapeHtml(__('Order Items')) ?></th>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                  <?php /*  <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th> */?>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>	

				<?php  
				foreach ($_order->getAllVisibleItems() as $_item) {
					 $order_item = $block->escapeHtml($_item->getName());
				} 
				?>
                    <tr>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Order #')) ?>" class="col id"><?= $block->escapeHtml($_order->getRealOrderId()) ?></td>
                        <td data-th="<?= $block->escapeHtmlAttr(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
						
                       <?php /* <td data-th="<?= $block->escapeHtmlAttr(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td> */?>
						
						<td data-th="<?= $block->escapeHtmlAttr(__('Order Items')) ?>" class="col items"><?php echo $order_item; ?></td>
						
                        <td data-th="<?= $block->escapeHtmlAttr(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
						
                      <?php /*  <td data-th="<?= $block->escapeHtmlAttr(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td> */?>
						
                        <td data-th="<?= $block->escapeHtmlAttr(__('Actions')) ?>" class="col actions">
                            <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                    ->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
		
		
		<div class="orders_page_mobile" style="display:none;">
		
		<?php foreach ($_orders as $_order) : ?>	

				<?php  
				foreach ($_order->getAllVisibleItems() as $_item) {
					 $order_item = $block->escapeHtml($_item->getName());
				} 
				?>

			<div class="order">

			<div class="order_no"><?= $block->escapeHtml(__('Order #')) ?><?= $block->escapeHtml($_order->getRealOrderId()) ?></div>
			<div class="order_date"><?= $block->formatDate($_order->getCreatedAt()) ?></div>

			<div class="oredr_contain_part">
			<h3><?= $block->escapeHtmlAttr(__('Order Items')) ?></h3>
			<div class="order_items"><?php echo $order_item; ?></div>
			<div class="order_total"><?= $_order->formatPrice($_order->getGrandTotal()) ?></div>
			</div>

			<div class="order_view">
			<a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                                <span><?= $block->escapeHtml(__('View Order')) ?></span>
                            </a>
			</div>

			</div>
			
			 <?php endforeach; ?>

		</div>


    </div>

