<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\Sales\Block\Order\Items $block */
?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?= $block->escapeHtmlAttr(__('Items Ordered')) ?>">
        <caption class="table-caption"><?= $block->escapeHtml(__('Items Ordered')) ?></caption>
        <thead>
            <?php if ($block->isPagerDisplayed()) : ?>
                <tr>
                    <td colspan="5" data-block="order-items-pager-top" class="order-pager-wrapper order-pager-wrapper-top">
                        <?= $block->getPagerHtml() ?>
                    </td>
                </tr>
            <?php endif ?>
            <tr>
                <th class="col name"><?= $block->escapeHtml(__('Item')) ?></th>
                <?php /* <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th> */?>
                <th class="col price"><?= $block->escapeHtml(__('Item Price')) ?></th>
                <th class="col qty"><?= $block->escapeHtml(__('Quantity')) ?></th>
                <th class="col subtotal"><?= $block->escapeHtml(__('Total Price')) ?></th>
            </tr>
        </thead>
        <?php $items = $block->getItems(); ?>
        <?php $giftMessage = ''?>
        <?php foreach ($items as $item) :
            if ($item->getParentItem()) :
                continue;
            endif;
            ?>
            <tbody>
                <?= $block->getItemHtml($item) ?>
                <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order_item', $item) && $item->getGiftMessageId()) : ?>
                    <?php $giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($item); ?>
                    <tr>
                        <td class="col options" colspan="5">
                            <a href="#"
                               id="order-item-gift-message-link-<?= (int) $item->getId() ?>"
                               class="action show"
                               aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                               data-item-id="<?= (int) $item->getId() ?>">
                                <?= $block->escapeHtml(__('Gift Message')) ?>
                            </a>
                            <?php $giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($item); ?>
                            <div class="order-gift-message" id="order-item-gift-message-<?= (int) $item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                   title="<?= $block->escapeHtmlAttr(__('Close')) ?>"
                                   aria-controls="order-item-gift-message-<?= (int) $item->getId() ?>"
                                   data-item-id="<?= (int) $item->getId() ?>"
                                   class="action close">
                                    <?= $block->escapeHtml(__('Close')) ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label"><?= $block->escapeHtml(__('From')) ?></strong><?= $block->escapeHtml($giftMessage->getSender()) ?></dt>
                                    <dt class="item-recipient"><strong class="label"><?= $block->escapeHtml(__('To')) ?></strong><?= $block->escapeHtml($giftMessage->getRecipient()) ?></dt>
                                    <dd class="item-message"><?= /* @noEscape */ $this->helper(\Magento\GiftMessage\Helper\Message::class)->getEscapedGiftMessage($item) ?></dd>
                                </dl>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            </tbody>
        <?php endforeach; ?>
        
    </table>


    <div class="orders_view_page_mobile" style="display:none;">
            <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
            ?>
            <?php foreach ($items as $item) :
                if ($item->getParentItem()) :
                    continue;
                endif;
            ?>
            <?php

                $qty = $item->getQtyOrdered();
                $product = $objectManager->create('Magento\Catalog\Model\Product')->load($item->getProductId());
                //echo 'hello';exit;
                $store = $objectManager->get('Magento\Store\Model\StoreManagerInterface')->getStore();
                $ImageUrl = $this->getUrl('pub/media').'catalog/category/placeholder.png';
                if($product->getImage()){                    
                    $ImageUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA) . 'catalog/product' . $product->getImage();
                }      

            ?>
            <div class="order_view"> 
                <div class="product_name"><?= $block->escapeHtml($item->getName()) ?></div>
                <div class="contain_part">
                <div class="left">
                        <div class="product_image"><img src="<?php echo $ImageUrl; ?>" /></div>
                </div>
                <div class="right">
                    <?php $options = $item->getProductOptions(); 
                        if(!empty($options['attributes_info'])) {
                            foreach($options['attributes_info'] as $option)  {  ?>
                                <div class="attribute"><?php echo $option['label'];?>: <?php echo $option['value'];?></div>
                            <?php  } } ?>
                         <div class="price"><?php echo $formattedPrice = $priceHelper->currency($item->getPrice(), true, false); ?></div>
                         <div class="part">
                            <div class="qty"><?php echo floatval($qty); ?></div>
                            <div class="total"><?php echo $formattedPrice = $priceHelper->currency($item->getRowTotal(), true, false); ?></div>
                         </div>
                      </div>
                   </div>
                </div>        
            <?php endforeach; ?>
        </div>


    </div>





<div class="right_part">
        <h1>Order Summary</h1>
        <table>
                <?php if ($block->isPagerDisplayed()) : ?>
                    <tr>
                        <td colspan="5" data-block="order-items-pager-bottom" class="order-pager-wrapper order-pager-wrapper-bottom">
                            <?= $block->getPagerHtml() ?>
                        </td>
                    </tr>
                <?php endif ?>
                <?= $block->getChildHtml('order_totals') ?>
        </table>
        <?php echo $this->getLayout()->createBlock("Magento\Sales\Block\Order\Info")->setTemplate("Magento_Sales::order/info.phtml")->toHtml() ?>
    </div>


<?php if ($giftMessage) : ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>
