<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $helper = $this->helper('Earthsquared\Customize\Helper\Data'); 
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();    
$stockItem = $objectManager->get('\Magento\CatalogInventory\Api\StockRegistryInterface');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to my Bag'); ?>
<?php $qtyinc = '';
$qtyvalue = '';
 ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>        
        <?php
        if($_product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE) {
              $_children = $_product->getTypeInstance()->getUsedProducts($_product);
              foreach ($_children as $child){ 
                //$product = $objectManager->get('Magento\Catalog\Model\Product')->load($child->getId());          
                $productStock = $stockItem->getStockItem($child->getId());    
                $qtyinc = $productStock->getQtyIncrements();            
              }           
        } else { 
                $productStock = $stockItem->getStockItem($_product->getId());    
                $qtyinc = $productStock->getQtyIncrements();
        }
        ?>        
          <div class="field qty retail">           
            <div class="control">
              <?php if($qtyinc == '') {
                  $qtyvalue = $block->getProductDefaultQty();
              } else {
                  $qtyvalue = $qtyinc;
              } ?>
                <input type="hidden"
                       name="qty"
                       id="qty"
                       min="0"
                       value="<?= $qtyvalue * 1 ?>"
                       title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                       class="input-text qty"
                       data-validate="<?= $block->escapeHtmlAttr(json_encode($block->getQuantityValidators())) ?>"
                       />
            </div>
          </div>                   
        <?php endif; ?>
        <div class="actions">
            <button type="submit"
                    title="<?= $block->escapeHtmlAttr($buttonTitle) ?>"
                    class="action primary tocart grey-btn"
                    id="product-addtocart-button" disabled>
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
