<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product additional attributes template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Attributes
 */
?>
<?php
    $_helper = $this->helper(Magento\Catalog\Helper\Output::class);
    $_product = $block->getProduct();
?>
<?php if ($_additional = $block->getAdditionalData()) :?>
<div class="product-coll" data-mage-init='{"collapsible":
        {
        "active":true,
            "openedState": "active",
            "saveState": false,
            "animate": true,
            "header": "[data-role=coll-title]",
            "content": "[data-role=coll-content]"
        }
    }'>
  <h3 class="action" data-role="coll-title">
    <?php echo __('More Information') ?>
  </h3>      
  <div class="coll-content" data-role="coll-content">
    <?php foreach ($_additional as $_data) :?>
        <div class="content-more-info">
         <div class="p-title"><?= $block->escapeHtml($_data['label']) ?></div>  
         <p><?= /* @noEscape */ $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></p> 
        </div>
    <?php endforeach; ?>
  </div>
</div>
<?php endif;?>

