<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $this->helper('Earthsquared\Customize\Helper\Data');
$_product = $block->getProduct();
if($helper->isCustomerLoggedIn()){      
    $productId= $_product->getId();
    $custid = $helper->getCustomerIdLoggedIn();
    $collection = $objectManager->create('Magento\Wishlist\Model\ResourceModel\Item\Collection');   
    $collection->addCustomerIdFilter($custid);
    $productIds = null;
    foreach ($collection as $item) {
        $productIds[] = $item->getProductId();   
    }
    if(in_array($productId,array($productIds))){ ?>
        <?php 
        if ($_product->isSaleable()) { ?>   
        <div class="mobileview wishlistp">
            <a href="<?php echo $this->getUrl('customize/index/index').'?cid='.$custid.'&pid='.$productId ?>" class="action towishlist" data-action="add-to-wishlist"><img src="<?php echo $this->getUrl('pub/media/icons/').'heart-fill.png' ?>" /></a>
        </div>
    <?php } } else { ?>
       <?php 
        if ($_product->isSaleable()) { ?>   
            <div class="mobileview wishlistp">
                <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><img src="<?php echo $this->getUrl('pub/media/icons/').'heart.png' ?>" /></a>
            </div>
        <?php } ?>
    <?php } ?>   
<?php } else { ?>
<?php if ($_product->isSaleable()) { ?>   
    <div class="mobileview wishlistp">
        <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><img src="<?php echo $this->getUrl('pub/media/icons/').'heart.png' ?>" /></a>
    </div>
<?php } } ?>
