<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
<?php $product = $block->getProduct(); ?>
<?php $productId = $product->getId(); ?>
    <a href="javascript:;"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
       <span><?= $block->escapeHtmlAttr(__('Add to Wishlist')) ?></span> 
        <img class="nhover-wish" src="<?php echo $this->getUrl('pub/media/icons/').'heart.png' ?>" />
        <img class="hover-wish" src="<?php echo $this->getUrl('pub/media/icons/').'heart-white.png' ?>" />
    </a> 
<?php endif; ?>
