<ul class="header-topicons">
	<li><a href="#"><img src="<?php echo $this->getUrl('pub/media/icons').'call.png' ?>" /></a></li>
	<li><a href="<?php echo $this->getUrl().'customer/account/' ?>"><img src="<?php echo $this->getUrl('pub/media/icons').'user.png' ?>" /></a></li>
	<li><a href="<?php echo $this->getUrl().'wishlist/' ?>"><img src="<?php echo $this->getUrl('pub/media/icons').'heart.png' ?>" /></a></li>
</ul>