<?php 
	$helper = $this->helper('Earthsquared\Customize\Helper\Data');
	$websiteid = $helper->getWebsiteId();
	if($websiteid == 1){ ?>
		<div class="section1"><a href="#" class="quickorder"><img src="<?php echo $this->getUrl('pub/media/icons/').'lightning.png' ?>" /><?php echo __('Quick Order Form'); ?></a></div>
	<?php } else { ?>
		<div class="section1"><a href="#" class="button-pink"><?php echo __('Trade Login'); ?></a></div>
	<?php } ?>	