<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
$helper = $this->helper('Earthsquared\Customize\Helper\Data');
if($helper->isCustomerLoggedIn()){  
    $custid = $helper->getCustomerIdLoggedIn();
    $collection = $objectManager->create('Magento\Wishlist\Model\ResourceModel\Item\Collection');   
    $collection->addCustomerIdFilter($custid);
    $productIds = null;
    foreach ($collection as $item) {
        $productIds[] = $item->getProductId();   
    }    
}
?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
        $imageDisplayAreaHover = 'category_page_grid-hover';
        $image_width = 314;
        $image_height = 314;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();

    ?>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php /*
                    $productImage = $block->getImage($_product, $imageDisplayArea);                                        

                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    */ ?>
                    <?php // Product Image ?>                                        
                    <?php /* <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo nhover"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>                        
                    </a>  <?php */ ?>
                    <?php 
                   // if($_product->getTypeId() == 'simple'){
                      $productImage = $_imagehelper->init($_product, $imageDisplayArea)->constrainOnly(true)->keepAspectRatio(TRUE)->keepFrame(true)->resize($image_width,$image_height);                      
                      $productImageUrl = $productImage->getUrl();
                      $productHoverImage = $_imagehelper->init($_product, $imageDisplayAreaHover)->constrainOnly(true)->keepAspectRatio(TRUE)->keepFrame(true)->resize($image_width,$image_height);
                      $productHoverImageUrl = $productHoverImage->getUrl();
                    ?>
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                           class="product photo product-item-photo"
                           tabindex="-1">
                        <span class="product-image-container" style="width:100%;">
                            <span class="product-image-wrapper" style="padding-bottom: 100%;">
                            <img class="product-image-photo" src="<?php echo $productImageUrl; ?>" alt="<?php echo $productImage->getLabel(); ?>" onmouseover="this.src='<?php echo ($productHoverImageUrl) ? $productHoverImageUrl : $productImageUrl ?>';" onmouseout="this.src='<?php echo $productImageUrl; ?>';" />
                            </span>
                        </span>    
                    </a> 
                <?php //} else { ?>
                    <?php /*
                    $productImage = $block->getImage($_product, $imageDisplayArea);                                        

                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>                                        
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo nhover"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>                        
                    </a>  
                <?php } */ ?>    
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
                        <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                        <?php if ($_product->isAvailable()) :?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php endif; ?>

                        <?php 
                        if($_product->getTypeId() == 'simple') 
                        {
                                $product_label = __("On Sale");
                                $orgprice = $_product->getPrice();
                                $specialprice = $_product->getSpecialPrice();
                                $specialfromdate = $_product->getSpecialFromDate();
                                $specialtodate = $_product->getSpecialToDate();
                                $today = time();
                                if(!$specialprice)
                                    $specialprice = $orgprice;
                                if($specialprice < $orgprice) {
                                    if((is_null($specialfromdate) && is_null($specialtodate)) || ($today >= strtotime($specialfromdate) && is_null($specialtodate)) || ($today <= strtotime($specialtodate) && is_null($specialfromdate)) || ($today >= strtotime($specialfromdate) && $today <= strtotime($specialtodate))){  ?>                                      
                                            <div class="product-label sale-label"><?php echo $product_label; ?></div>                                     
                                    <?php }
                                }
                            }
                        ?>
                            <div class="product-detail-action">
                                <div class="action-button">
                                    <?php if ($_product->isSaleable()) :?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $block->escapeHtmlAttr($_product->getSku()) ?>"
                                              action="<?= $block->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="tocart">
                                                <span><?= $block->escapeHtmlAttr(__('Add to Bag')) ?></span>    
                                                <img src="<?php echo $this->getUrl('pub/media/icons/').'shopping-bag.png' ?>" />
                                            </button>
                                        </form>
                                    <?php //else :?>
                                        <?php /* if ($_product->isAvailable()) :?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else :?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; */ ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="action-button"<?= strpos($pos, $viewMode . '-secondary') ? $block->escapeHtmlAttr($position) : '' ?>> 
                                    
                                        <?php  if($helper->isCustomerLoggedIn()) { 
                                              $productId = $_product->getId();
                                              $custid = $helper->getCustomerIdLoggedIn();
                                          ?>                             
                                                <?php if(in_array($productId,array($productIds))) { ?>
                                                    <a href="<?php echo $this->getUrl('customize/index/index').'?cid='.$custid.'&pid='.$productId ?>" class="action towishlist" data-action="add-to-wishlist">
                                                        <span><?= $block->escapeHtmlAttr(__('Add to Wishlist')) ?></span> 
                                                        <img src="<?php echo $this->getUrl('pub/media/icons/').'heart-fill.png' ?>" />
                                                    </a>                                               
                                                <?php } else { ?> 
                                                <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                                <?php endif; ?>                                                                 
                                               <?php } ?>
                                        <?php } else {  ?>
                                            <?php if ($addToBlock = $block->getChildBlock('addto')) :?>
                                                <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                            <?php endif; ?>        
                                        <?php  } ?>
                                
                                </div>                              
                            </div>                                                
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <div class="bottom-toolbar">
        <?= $block->getToolbarHtml() ?>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
