<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Framework\View\Element\AbstractBlock $block
 */

// We should use strlen function because coupon code could be "0", converted to bool will lead to false
$hasCouponCode = (bool) strlen($block->getCouponCode());
?>
<div class="block discount tread"
     id="block-discount_trade"
     data-mage-init='{"collapsible":{"active": <?= $hasCouponCode ? 'true' : 'false' ?>, "openedState": "active", "saveState": false}}'
>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('+ Apply Promotional Code')) ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
        <form id="discount-coupon-form"
              action="<?= $block->escapeUrl($block->getUrl('checkout/cart/couponPost')) ?>"
              method="post"
              data-mage-init='{"discountCode":{"couponCodeSelector": "#coupon_code",
                                               "removeCouponSelector": "#remove-coupon",
                                               "applyButton": "button.action.apply",
                                               "cancelButton": "button.action.cancel"}}'>
            <div class="fieldset coupon<?= $hasCouponCode ? ' applied' : '' ?>">
                <input type="hidden" name="remove" id="remove-coupon" value="0" />
                <div class="field">
                    <div class="control">
                        <input type="text"
                               class="input-text"
                               id="coupon_code"
                               name="coupon_code"
                               value="<?= $block->escapeHtmlAttr($block->getCouponCode()) ?>"
                               placeholder="<?= $block->escapeHtmlAttr(__('Apply Promotional Code')) ?>"
                        />
                    </div>
                </div>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action primary submit-coupon" type="button" value="<?= $block->escapeHtmlAttr(__('Apply')) ?>">
                            <span><?= $block->escapeHtml(__('Apply')) ?></span>
                        </button>
                    </div>
                </div>
            </div>
            <?php if ($hasCouponCode) :?>
                <div class="message message-success success loaded">
                    <div>
                      <?= $block->escapeHtml(__('Promotional Code %1 successfully applied. You received a discount of <span>%2</span>',$block->getCouponCode(), $block->getDiscountAmount()),['span']) ?>
                      <a href="JavaScript:void(0);" class='change-coupon'>remove</a></div>
                </div>
            <?php endif; ?>
            <div class="message" id="ajax_message">
                <div></div>
            </div>
            <?php if (!$hasCouponCode) : ?>
                <?= /* @noEscape */ $block->getChildHtml('captcha') ?>
            <?php endif; ?>
        </form>
    </div>
</div>
<script type="text/x-magento-init">
    { 
        "#discount-coupon-form": {
            "submitCoupon": {}
        }
    }
</script>