<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<?php
/** @var $block \Amasty\Cart\Block\Product\Minipage */

// @codingStandardsIgnoreLine
$helper = $this->helper(\Magento\Catalog\Helper\Output::class);
$product = $block->getProduct();
$rating = $block->getRatingSummary($product);
$productName = $helper->productAttribute($product, $product->getName(), 'name');
$productSku = $helper->productAttribute($product, $product->getSku(), 'sku');
?>
<?php /* 
<p class="amcart-product-notice">
    <?= $block->escapeHtml(__('Please choose the options for your item')); ?>
</p> */ ?>
<div class="product-item-info product-info-main">
    <div class="ampage-top-info">
        <p class="am-title">
            <?= $block->escapeHtml($productName); ?>
        </p>
        <div class="psku"><?php echo __('Product Reference: ') ?><?= $block->escapeHtml($productSku); ?></div>        
        <div class="am-price product-info-price"><?= $block->renderPriceHtml(); ?></div>
    </div>

    <div class="am-photo-container">
        <a href="<?= $block->escapeUrl($product->getProductUrl()); ?>"
           title="<?= $block->escapeHtml($productName); ?>"
           tabindex="-1"
           class="product-item-photo">
            <?= /* @noEscape */ $block->getImageBlock($product, 'amasty_cart_popup_image'); ?>
        </a>
    </div>

    <div class="ampage-bottom-info">       
        <p><?= /* @noEscape */ $block->getOptions(); ?></p>
        <?php echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('product_details_three_benefits')
          ->toHtml(); ?>
    </div>    
     <a class="viewfull-details" href="<?php echo $product->getProductUrl() ?>"><?php echo __('View full details')?></a>       
</div>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var priceBoxes = $('.am-price [data-product-id=<?= $block->escapeHtml($product->getId()) ?>]');

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?= /* @noEscape */ $block->getJsonConfig() ?>});
    });
</script>
