<?php
/**
 * Copyright © 2018 Porto. All rights reserved.
 */

?>
<?php
/**
 * Top menu for store
 *
 * @see \Smartwave\Megamenu\Block\Topmenu
 */
?>
<?php
    $_helper = $this->helper('Smartwave\Megamenu\Helper\Data');
    $_config = $_helper->getConfig('sw_megamenu');
    $helper = $this->helper('Earthsquared\Customize\Helper\Data');
    $columnsLimit = 0;
    if($_config['general']['enable']) {
?>
<?php $_menu = $block->getMegamenuHtml(); ?>
<div class="mobileview">
    <a href="javascript:;" class="closeicon"><img src="<?php echo $this->getUrl('pub/media/headerimages/').'close-i.png' ?>" /></a> 
    <ul class="wishcart">        
        <?php echo $this->getLayout()->createBlock("Magento\Wishlist\Block\Link")->setTemplate("Magento_Wishlist::link.phtml")->toHtml(); ?>   
        <?php echo $this->getLayout()->createBlock("Magento\Checkout\Block\Cart\Sidebar")->setTemplate("Magento_Checkout::cart/minicart-mobile.phtml")->toHtml(); ?>           
    </ul>
</div>
<nav class="navigation sw-megamenu" role="navigation">
    <ul>
        <?php echo $_menu; ?>
    </ul>
</nav>

<script type="text/javascript">
    require([
        'jquery',
        'Smartwave_Megamenu/js/sw_megamenu'
    ], function ($) {
        $(".sw-megamenu").swMegamenu();
        $('.closeicon').on('click',function(){ 
            console.log('test');           
            $('html').removeClass('nav-open');
            $('html').removeClass('nav-before-open');
        });          
        $(window).scroll(function() {
            var y = $(this).scrollTop();
            var top = $('.page-header').height();
            //var navigation = $('.nav-sections.sections').height();
           // var totalh = top + navigation;
            if (y > top) {
                $('.page-wrapper').addClass('stickymenu');
            } else {
                $('.page-wrapper').removeClass('stickymenu');
            }
        });      
    });
</script>
<?php
    } else {
?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit); ?>

<nav class="navigation sw-megamenu" role="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?php /* @escapeNotVerified */ echo $_menu; ?>
    </ul>
</nav>

<?php
    }
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$customerSession = $objectManager->get('Magento\Customer\Model\Session');
?>
<div class="mobileview">    
<ul class="loginreg">
    <?php if($customerSession->isLoggedIn()) { ?>
        <li><a class="logout" href="<?php echo $this->getUrl().'customer/account/logout' ?>"><?php echo __("Log Out") ?></a></li>
        <li><a href="<?php echo $this->getUrl().'customer/account' ?>"><?php echo __("My Account") ?></a></li>
    <?php } else { ?>
        <li><a href="<?php echo $this->getUrl().'customer/account' ?>"><?php echo __("Sign In") ?></a></li>
        <li><a href="<?php echo $this->getUrl().'customer/account/create' ?>"><?php echo __("Register") ?></a></li>
   <?php } ?>   

</ul>
<div class="tradesocial col-xs-12 nopadding">
    <div class="col-xs-12 quick">        
            <a href="#" class="quickorder"><img src="<?php echo $this->getUrl('pub/media/icons/').'lightning.png' ?>" /><?php echo __('Quick Order Form'); ?></a>
    </div>
    <div class="col-xs-12 socialtrade">
        <ul class="socialiconsm">
            <li><a target="_blank" href="https://www.facebook.com/EarthSquaredLtd/">
                <img src="<?php echo $this->getUrl('pub/media/headerimages/').'facebook-h.png' ?>" />
            </a></li>
            <li><a target="_blank" href="https://twitter.com/earthsquaredltd"><img src="<?php echo $this->getUrl('pub/media/headerimages/').'twitter-h.png' ?>" /></a></li>
            <li><a target="_blank" href="https://www.instagram.com/earth_squared"><img src="<?php echo $this->getUrl('pub/media/headerimages/').'instagram-h.png' ?>" /></a></li>
        </ul>
    </div>
</div>
</div>
