<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist $block */
?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()) : ?>
	
		<a href="#"
	       data-post='<?= /* @noEscape */ $block->getMoveFromCartParams() ?>'
	       class="use-ajax action towishlist action-towishlist trade">
	       	<img src="<?php echo $this->getUrl('pub/media/icons/').'bookmark-cart.png' ?>" />
	        <span><?= $block->escapeHtml(__('Save for later')) ?></span>
	    </a>
	
<?php endif ?>
