<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<small class="copyright footerc">
	<div class="max-width-section">
    	<span><?= $block->escapeHtml($block->getCopyright()) ?></span>
    	<?php echo $this->getLayout()
          ->createBlock('Magento\Cms\Block\Block')
          ->setBlockId('footer_checkout')
          ->toHtml(); ?>
	</div>

</small>
