<?php 
  $helper = $this->helper('Earthsquared\Customize\Helper\Data');  
?>
<ul class="header-topicons">
	<li><a href="javascript:void(0)" class="search-toggle-icon"><img src="<?php echo $this->getUrl('pub/media/icons/').'loupe.png' ?>" /></a></li>
	<li><a href="<?php echo $this->getUrl('contact') ?>"><img src="<?php echo $this->getUrl('pub/media/icons').'call.png' ?>" /></a></li>  
  <?php if($helper->isCustomerLoggedIn()) { ?>
	<li><a href="<?php echo $this->getUrl().'customer/account/' ?>"><img src="<?php echo $this->getUrl('pub/media/icons').'user.png' ?>" /></a></li>
  <?php } else { ?>
  <li><a href="<?php echo $this->getUrl().'customer/account/' ?>"><img src="<?php echo $this->getUrl('pub/media/icons').'user.png' ?>" /></a></li>
  <?php } ?>
  <?php echo $this->getLayout()->createBlock("Magento\Wishlist\Block\Link")->setTemplate("Magento_Wishlist::topwishlink.phtml")->toHtml(); ?>  

</ul>

<script>  
            require([
              'jquery'   
            ], function ($) {
              $(document).ready(function(event){
                  $('.search-toggle-icon,.search-toggle-icon1').on('click',function(){  
                    if($('.block-search').hasClass('active'))                
                    {
                      $('.block-search').removeClass('active');  
                    } else {
                      $('.block-search').addClass('active');
                    }
                    
                  });
                  $('.search-close').on("click",function(){
                    $('.block-search').removeClass('active');  
                  });
                  $('.wishtop').on('click',function(){ 
                      $('.topwishlistitems').toggle();
                  });                                    
              });
            });

</script>