<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */
?>
<?php
$helper = $this->helper('Earthsquared\Customize\Helper\Data');
$websiteid = $helper->getWebsiteId();
$_product = $helper->getCurrentProduct(); 
if($helper->isCustomerLoggedIn()){	
	$custid = $helper->getCustomerIdLoggedIn();	
	$pid = $_product->getId();
	$wish = $helper->getWishlistItemcollection($custid);
    $items = $wish->getItemCollection();
    if(count($items) > 0){
	?>		
			<a href="<?php echo $this->getUrl('customize/index/index').'?cid='.$custid.'&pid='.$pid ?>" class="action towishlist" data-action="add-to-wishlist">
				<span><?= $block->escapeHtml(__('Remove From Wish List')) ?></span>
			</a>		
	<?php
	} else {
		if ($_product->isSaleable()) { ?>				
				<a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist">
					<?php if($websiteid == 1) { ?>
						<span><?= $block->escapeHtml(__('Save for Later')) ?></span>
					<?php } else { ?>
						<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
					<?php } ?>
				</a>			
		<?php }		
	} 
} else {
if ($_product->isSaleable()) { ?>		
		<a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist">
					<?php if($websiteid == 1) { ?>
						<span><?= $block->escapeHtml(__('Save for Later')) ?></span>
					<?php } else { ?>
						<span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
					<?php } ?>
		</a>
	
<?php }	} ?>
