<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
    <a href="#"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Save for Later')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Save for Later')) ?>"
       data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>'
       data-action="add-to-wishlist"
       role="button">
       <span><?= $block->escapeHtmlAttr(__('Save for Later')) ?></span> 
        <img class="nhover-wish" src="<?php echo $this->getUrl('pub/media/icons/').'bookmark.png' ?>" />        
    </a>
<?php endif; ?>
