<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
<?php $product = $block->getProduct(); ?>
<?php $productId = $product->getId(); ?>
<?php $productname = $product->getName(); ?>
    <a href="javascript:;"
       class="action towishlist"
       title="<?= $block->escapeHtmlAttr(__('Save for Later')) ?>"
       aria-label="<?= $block->escapeHtmlAttr(__('Save for Later')) ?>"       
      >
       <span><?= $block->escapeHtmlAttr(__('Save for Later')) ?></span> 
        <img class="nhover-wish" src="<?php echo $this->getUrl('pub/media/icons/').'bookmark.png' ?>" />        
    </a>
<?php endif; ?>
