<?php 
$id = [253];
$categoryProducts = $block->getProductCollectionByCategory($id);
?>
<div class="featurep-collection">
<?php 
foreach ($categoryProducts as $product) { ?>    
	<?php $image_url = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_small_image')->constrainOnly(true)->keepAspectRatio(true)->keepTransparency(true)->keepFrame(true)->setImageFile($product->getFile())->resize(288, 288)->getUrl(); ?>
	<div class="item col-md-3">		
		<a href="<?php echo $product->getProductUrl() ?>">
			<img src="<?php echo $image_url ?>" alt="<?php echo $product->getName(); ?>" title="<?php echo $product->getName(); ?>" />
			<div class="product-detail">
				<div class="product-name"><?php echo $product->getName(); ?></div>
				<div class="product-price"><?php echo $block->getProductPrice($product->getPrice()); ?></div>
			</div>
		</a>
	</div>
<?php 
}
?>