<?php 
const PARAM_NAME_BASE64_URL = 'r64';
const PARAM_NAME_URL_ENCODED = 'uenc';
use Magento\Framework\App\Action\Action;

$id = [253];
$categoryProducts = $block->getProductCollectionByCategory($id);
//echo count($categoryProducts);
?>
<div class="featurep-collection">
<?php 
foreach ($categoryProducts as $product) { ?>    
	<?php $image_url = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_small_image')->constrainOnly(true)->keepAspectRatio(true)->keepTransparency(true)->keepFrame(true)->setImageFile($product->getFile())->resize(288, 288)->getUrl();
	 ?>
	<div class="item col-md-3 col-sm-3">		
			<a href="<?php echo $product->getProductUrl() ?>">
			<?php 
				if($product->getLifestyleImage() != "")
				{
					$image_hover_url = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_small_image_hover')->constrainOnly(true)->keepAspectRatio(true)->keepTransparency(true)->keepFrame(true)->setImageFile($product->getFile())->resize(288, 288)->getUrl();
					?>
					<img src="<?php echo $image_hover_url; ?>" onmouseover="this.src='<?php echo ($image_url) ? $image_url : $image_url ?>';" onmouseout="this.src='<?php echo $image_hover_url; ?>';" alt="<?php echo $product->getName(); ?>" title="<?php echo $product->getName(); ?>" />	
				<?php }  else { ?>
					<img src="<?php echo $image_hover_url; ?>" alt="<?php echo $product->getName(); ?>" title="<?php echo $product->getName(); ?>" />	
				<?php } ?>

			<div class="product-detail">
				<div class="product-name"><?php echo $product->getName(); ?></div>
				<div class="product-price">
					<?php if($product->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){ ?>
						<?php echo $block->getProductPrice($product->getFinalPrice()); ?>						
				<?php } else { 
						echo $block->getProductPrice($product->getPrice());
				} ?>
				</div>
			</div>
			</a>
			    <?php $postParams = $block->getAddToCartPostParams($product); ?>    			
			<div class="product-detail-action">
				<div class="action-button">
				    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
				        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
				        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
				        <?php echo $block->getBlockHtml('formkey')?>
				        <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
				            <button type="submit"
				                    title="<?php echo $block->escapeHtml(__('Add to Bag')); ?>"
				                    class="tocart">
				                <span><?php echo $block->escapeHtml(__('Add to Bag')); ?></span>    
				               <img src="<?php echo $this->getUrl('pub/media/icons/').'shopping-bag.png' ?>" />
				            </button>
				    </form>
				</div>
				<div class="action-button">					
					<a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($product) ?>' class="action towishlist" data-action="add-to-wishlist"><span><?php echo $block->escapeHtml(__('Add to Wishlist')); ?></span>    <img src="<?php echo $this->getUrl('pub/media/icons/').'heart.png' ?>" /></a>
				</div>
		</div>
		
	</div>
<?php 
}
?>
</div>
<script>		
require(['jquery', 'mageplaza/core/owl.carousel'], function ($) {
$(document).ready(function () {
	var countproducts = '<?php echo count($categoryProducts); ?>';
    $(window).on("resize", function (e) {
        checkScreenSize();
    });

    checkScreenSize();

    function checkScreenSize(){
        var newWindowWidth = $(window).width();
        if (newWindowWidth <= 767) {
	 		$('.featurep-collection').addClass('owl-carousel');
	 		$('.featurep-collection').addClass('owl-theme');
	 		$('.featurep-collection').owlCarousel({
				stagePadding: 40,
				loop:false,
				margin:10,    		
	    		dots:true,
	    		nav:false,
			    responsive:{
			        0:{
			            items:1
			        },
			        600:{
			            items:3
			        }		        
			    }
	 		});
        }
        else
        {
            if(countproducts > 4){
				$('.featurep-collection').addClass('owl-carousel');
				$('.featurep-collection').addClass('owl-theme');
				$('.featurep-collection').owlCarousel({			
							loop:true,
							margin:10,    		
				    		dots:true,
				    		nav:false,
						    items:4
				});	
            } else {
            	 $('.featurep-collection').owlCarousel('destroy');
                 $('.featurep-collection').removeClass('owl-carousel');
            }
        }
    }
}); 
});
</script>

