<?php 
const PARAM_NAME_BASE64_URL = 'r64';
const PARAM_NAME_URL_ENCODED = 'uenc';
use Magento\Framework\App\Action\Action;

$id = [253];
$categoryProducts = $block->getProductCollectionByCategory($id);
?>
<div class="featurep-collection">
<?php 
foreach ($categoryProducts as $product) { ?>    
	<?php $image_url = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_small_image')->constrainOnly(true)->keepAspectRatio(true)->keepTransparency(true)->keepFrame(true)->setImageFile($product->getFile())->resize(288, 288)->getUrl();
	 ?>
	<div class="item col-md-3">		
		<a href="<?php echo $product->getProductUrl() ?>">
			<?php 
				if($product->getLifestyleImage() != "")
				{
					$image_hover_url = $this->helper('Magento\Catalog\Helper\Image')->init($product, 'product_small_image_hover')->constrainOnly(true)->keepAspectRatio(true)->keepTransparency(true)->keepFrame(true)->setImageFile($product->getFile())->resize(288, 288)->getUrl();
					?>
					<img src="<?php echo $image_url; ?>" onmouseover="this.src='<?php echo ($image_hover_url) ? $image_hover_url : $image_url ?>';" onmouseout="this.src='<?php echo $image_url; ?>';" alt="<?php echo $product->getName(); ?>" title="<?php echo $product->getName(); ?>" />	
				<?php }  else { ?>
					<img src="<?php echo $image_url; ?>" alt="<?php echo $product->getName(); ?>" title="<?php echo $product->getName(); ?>" />	
				<?php } ?>

			<div class="product-detail">
				<div class="product-name"><?php echo $product->getName(); ?></div>
				<div class="product-price"><?php echo $block->getProductPrice($product->getPrice()); ?></div>
			</div>
			</a>
			    <?php $postParams = $block->getAddToCartPostParams($product); ?>    			
			<div class="product-detail-action">
				<div class="action-button">
				    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
				        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
				        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
				        <?php echo $block->getBlockHtml('formkey')?>
				        <?php $storeManager = \Magento\Framework\App\ObjectManager::getInstance()->get('Magento\Store\Model\StoreManagerInterface'); ?>
				            <button type="submit"
				                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
				                    class="tocart">
				               <img src="<?php echo $this->getUrl('pub/media/icons/').'shopping-bag.png' ?>" />
				            </button>
				    </form>
				</div>
				<div class="action-button">
					<?php echo $this->getLayout()->createBlock("Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist")->setTemplate("Magento_Wishlist::catalog/product/list/addto/wishlist.phtml")->toHtml() ?>
				</div>
		</div>
		
	</div>
<?php 
}
?>