<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<div class="actions">
    <?php $_order = $block->getOrder() ?>   
    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>    
        <a href="#" data-post='<?=
        /* @noEscape */ $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
            ->getPostData($block->getReorderUrl($_order))
        ?>' class="action order">
            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
        </a>
    <?php endif ?>   
  <?php if ($_order->getInvoiceCollection()->count()) { ?>    
      <a href="<?php echo $this->getUrl('sales/order/printInvoice/').'order_id/'.$_order->getEntityId() ?>"
         class="action print"
         target="_blank"
         rel="noopener">
          <span><?= $block->escapeHtml(__('PDF Invoice')) ?></span>
      </a>    
  <?php } ?>    
    <?= $block->getChildHtml() ?>
</div>
