<div class="quicksearchbox">
	<div id="quicksearchform">	
		<div class="fieldset">
			<div class="control">
				<div class="field">
					<label><img src="<?php echo $this->getUrl().'pub/media/icons/loupe.png' ?>"></label>
					<input type="text" name="quicksearch" id="quicksearch" placeholder="<?php echo __('Search by product name or product reference') ?>">
				</div>
			</div>
		</div>
	</div>
</div>	