<div class="need_morehelp desktopview">
<span>Need help?</span>
	<div class="tooltip_text" style="display:none;">
		<h4>How to use quick order form</h4>
		<ol>
			<li>Add the quantities you want of each product</li>
			<li>You'll be able to see your selected items on the right</li>
			<li>Once you're happy with your selected items. click on Add to my Bag</li>
		</ol>
	</div>
</div>
<div class="need_morehelp mobileview">
<span>Need help?</span>
	<div class="tooltip_text" style="display:none;">
		<h4>How to use quick order form</h4>
		<ol>
			<li>Add the quantities you want of each product</li>
			<li>You'll be able to see your selected items on the right</li>
			<li>Once you're happy with your selected items. click on Add to my Bag</li>
		</ol>
	</div>
</div>