<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$_helper = $this->helper('Earthsquared\Customize\Helper\Data');
$websiteid = $_helper->getWebsiteId();
if($_helper->isMobile()){ ?>
<div class="cart item cartmobile mobileview">
    <div class="product-item-details">
        <strong class="product-item-name">
            <?php if ($block->hasProductUrl()) :?>
                  <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
            <?php else :?>
                   <?= $block->escapeHtml($block->getProductName()) ?>
            <?php endif; ?>
        </strong>
    </div>
    <div class="main-cart-section">
        <div class="cart-section1">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>            
        </div>
        <div class="cart-section2">
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>  
                <?php if ($canApplyMsrp) :?>
                    <div class="col msrp">
                        <span class="pricing msrp">
                            <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                            <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                            <a href="#" class="action help map"
                               id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                               data-mage-init='{"addToCart":{
                                                    "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                                    "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                                    "showAddToCart": false
                                                    }
                                                }'
                            >
                                <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                            </a>
                        </span>
                    </div>
                <?php else :?>
                    <div class="col price">
                        <?= $block->getUnitPriceHtml($_item) ?>
                    </div>
                <?php endif; ?>                          
                <div class="qty-subtotal">
                    <div class="field qty">
                        <div class="control qty cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                             
                            <div href="javascript:void(0)" class="qty-dec">-</div>                                  
                               <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                                   name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                                   data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                                   value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                                   type="number"
                                   size="4"
                                   title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                                   class="input-text qty"
                                   maxlength="12"
                                   data-validate="{required:true,'validate-greater-than-zero':true}"
                                   data-role="cart-item-qty"/>
                                <div href="javascript:void(0)" class="qty-inc">+</div> 
                         
                        </div>
                    </div> 
                    <div class="col subtotal">
                        <?php if ($canApplyMsrp) :?>
                            <span class="cart msrp subtotal">--</span>
                        <?php else :?>
                            <?= $block->getRowTotalHtml($_item) ?>
                        <?php endif; ?>
                    </div>            
                </div>   
        </div>
        <div class="actions-toolbar">
            <?= /* @noEscape */ $block->getActions($_item) ?>
        </div>
    </div>                   
</div>
<?php } else { ?>
<tbody class="cart item desktopview">
    <tr class="item-info">
        <td data-th="<?= $block->escapeHtmlAttr(__('Item')) ?>" class="col item">
            <?php if ($block->hasProductUrl()) :?>
                <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                   title="<?= $block->escapeHtmlAttr($block->getProductName()) ?>"
                   tabindex="-1"
                   class="product-item-photo">
            <?php else :?>
                <span class="product-item-photo">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
            <?php if ($block->hasProductUrl()) :?>
                </a>
            <?php else :?>
                </span>
            <?php endif; ?>
            <div class="product-item-details">
                <strong class="product-item-name">
                    <?php if ($block->hasProductUrl()) :?>
                        <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                    <?php else :?>
                        <?= $block->escapeHtml($block->getProductName()) ?>
                    <?php endif; ?>
                </strong>
                <?php if ($_options = $block->getOptionList()) :?>
                    <dl class="item-options">
                        <?php foreach ($_options as $_option) :?>
                            <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                            <dd>
                                <?php if (isset($_formatedOptionValue['full_view'])) :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['full_view']) ?>
                                <?php else :?>
                                    <?= $block->escapeHtml($_formatedOptionValue['value'], ['span', 'a']) ?>
                                <?php endif; ?>
                            </dd>
                        <?php endforeach; ?>
                    </dl>
                <?php endif;?>
                <div class="actions-toolbar">
                    <?= /* @noEscape */ $block->getActions($_item) ?>
                </div>
                <?php if ($messages = $block->getMessages()) :?>
                    <?php foreach ($messages as $message) :?>
                        <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                            <div><?= $block->escapeHtml($message['text']) ?></div>
                        </div>
                    <?php endforeach; ?>
                <?php endif; ?>
                <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                <?php if ($addInfoBlock) :?>
                    <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                <?php endif;?>
            </div>
        </td>

        <?php if ($canApplyMsrp) :?>
            <td class="col msrp" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <span class="pricing msrp">
                    <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                    <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                    <a href="#" class="action help map"
                       id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                       data-mage-init='{"addToCart":{
                                            "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                            "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                            "showAddToCart": false
                                            }
                                        }'
                    >
                        <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                    </a>
                </span>
            </td>
        <?php else :?>
            <td class="col price" data-th="<?= $block->escapeHtmlAttr(__('Price')) ?>">
                <?= $block->getUnitPriceHtml($_item) ?>
            </td>
        <?php endif; ?>
        <td class="col qty" data-th="<?= $block->escapeHtmlAttr(__('Qty')) ?>">
            <div class="field qty">
                <div class="control qty cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty trade">                   
                               <div href="javascript:void(0)" class="qty-dec">-</div> 
                               <input id="cart-<?php /* @escapeNotVerified */ echo $_item->getId() ?>-qty"
                                   name="cart[<?php /* @escapeNotVerified */ echo $_item->getId() ?>][qty]"
                                   data-cart-item-id="<?php /* @escapeNotVerified */ echo $_item->getSku() ?>"
                                   value="<?php /* @escapeNotVerified */ echo $block->getQty() ?>"
                                   type="number"
                                   size="4"
                                   title="<?php echo $block->escapeHtml(__('Qty')); ?>"
                                   class="input-text qty trade"
                                   maxlength="12"
                                   data-validate="{required:true,'validate-greater-than-zero':true}"
                                   data-role="cart-item-qty"/>
                                <div href="javascript:void(0)" class="qty-inc">+</div> 
                </div>
            </div>
        </td>

        <td class="col subtotal" data-th="<?= $block->escapeHtmlAttr(__('Subtotal')) ?>">
            <?php if ($canApplyMsrp) :?>
                <span class="cart msrp subtotal">--</span>
            <?php else :?>
                <?= $block->getRowTotalHtml($_item) ?>
            <?php endif; ?>
        </td>
    </tr>   
</tbody>
<?php } ?>


<script type="text/javascript">
    require(["jquery"],function($){        
        $(".qty-inc").unbind('click').click(function(){
            if($(this).parents('.field.qty').find("input.input-text.qty").is(':enabled')){
                $(this).parents('.field.qty').find("input.input-text.qty").val((+$(this).parents('.field.qty').find("input.input-text.qty").val() + 1) || 0);
                $(this).parents('.field.qty').find("input.input-text.qty").trigger('change');
                $(this).focus();
            }
        });
        $(".qty-dec").unbind('click').click(function(){
            if($(this).parents('.field.qty').find("input.input-text.qty").is(':enabled')){
                $(this).parents('.field.qty').find("input.input-text.qty").val(($(this).parents('.field.qty').find("input.input-text.qty").val() - 1 > 0) ? ($(this).parents('.field.qty').find("input.input-text.qty").val() - 1) : 0);
                $(this).parents('.field.qty').find("input.input-text.qty").trigger('change');
                $(this).focus();
            }
        });
    });
</script>