<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Contact\Block\ContactForm $block */
?>
<?php
echo $this->getLayout()
->createBlock('Magento\Cms\Block\Block')
->setBlockId('contact_form')
->toHtml();
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <fieldset class="fieldset">
        <h2><span class="title_bg"></span><?= $block->escapeHtml(__('Send us a Message')) ?></h2>
		
		<div class="name">
		  <input type="text" name="name" id="name" class="inputText" placeholder="First Name*" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('name') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" data-validate='{"required":true}' data-msg-required="Please enter your first name"/>
		</div>
				
		<div class="lname">
		  <input type="text" name="lname" id="lname" class="inputText" placeholder="Last Name*" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('lname') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" data-validate='{"required":true}' data-msg-required="Please enter your last name"/>
		</div>
		
		<div class="email">
		  <input type="email" name="email" id="email" class="inputText" placeholder="Email*" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('email') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" data-msg-required="Please enter your email" data-validate="{required:true, 'validate-email':true}" />
		</div>
		
      
		<div class="comment">
		  <textarea type="comment" name="comment" id="comment" cols="5" rows="3" placeholder="Message*" class="inputText" value="<?= $block->escapeHtmlAttr($this->helper(\Magento\Contact\Helper\Data::class)->getPostValue('comment') ?: $this->helper(\Magento\Contact\Helper\Data::class)->getUserName()) ?>" data-validate='{"required":true}' data-msg-required="Please enter a message"></textarea>
		</div>
		
		
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

<style>
input:focus::-webkit-input-placeholder , textarea:focus::-webkit-input-placeholder {
    font-size: .75em;
    position: relative;
    top: -15px; 
    transition: 0.2s ease-out;
}

input::-webkit-input-placeholder , textarea::-webkit-input-placeholder {
    transition: 0.2s ease-in;
}

input[type="text"]:focus, input[type="password"]:focus, textarea:focus {
    padding-top: 10px;
    transition: 0.2s ease-in;
}

input[type="text"], input[type="password"], textarea {
    transition: 0.2s ease-in;
}

</style>

