<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter custom-select">    
    <label class="sorter-label init"><?= $block->escapeHtml(__('Sort By')) ?><span></span></label>
    <div id="sorter" data-role="sorter" class="sorter-options desk">
      <ul class="sortorder-options">      
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>                    
            <li data-role="sorter" data-value="<?= /* @escapeNotVerified */ $_key?>" 
               <?php if ($block->isOrderCurrent($_key)): ?> 
                 class="active"
               <?php endif; ?> 
               >
               <?= $block->escapeHtml(__($_order)) ?>
            </li> 
        <?php endforeach; ?>          
      </ul>    
    </div>
    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>
<script type="text/javascript">
            require([
              'jquery'   
            ], function ($) {
            $(document).ready(function(){  
                if($("ul.sortorder-options li").hasClass("active")){
                    var liactive = $('ul.sortorder-options li.active').text();
                    $('.custom-select label span').text(liactive);
                }
                $(".custom-select label.init").on("click", function() {
                  $(this).next("#sorter").toggle();
              });
     
            });
          });
</script>