<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $this->helper('Earthsquared\Customize\Helper\Data');
$_product = $block->getProduct();
if($helper->isCustomerLoggedIn()){      
    $productId= $_product->getId();
    $custid = $helper->getCustomerIdLoggedIn();
    $collection = $objectManager->create('Magento\Wishlist\Model\ResourceModel\Item\Collection');   
    $collection->addCustomerIdFilter($custid);
    $productIds = null;
    foreach ($collection as $item) {
        $productIds[] = $item->getProductId();   
    }
    if(in_array($productId,array($productIds))){ ?>
        <?php 
        if ($_product->isSaleable()) { ?>   
        <div class="mobileview wishlistp">
            <a href="<?php echo $this->getUrl('customize/index/index').'?cid='.$custid.'&pid='.$productId ?>" class="action towishlist" data-action="add-to-wishlist"><img src="<?php echo $this->getUrl('pub/media/icons/').'heart-fill.png' ?>" /></a>
        </div>
    <?php } } else { ?>
       <?php 
        if ($_product->isSaleable()) { ?>   
            <div class="mobileview wishlistp">
                <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><img src="<?php echo $this->getUrl('pub/media/icons/').'bookmark.png' ?>" /></a>
            </div>
        <?php } ?>
    <?php } ?>   
<?php } else { ?>
<?php if ($_product->isSaleable()) { ?>   
    <div class="mobileview wishlistp">
        <a href="#" data-post='<?php  echo $this->helper('Magento\Wishlist\Helper\Data')->getAddParams($_product) ?>' class="action towishlist" data-action="add-to-wishlist"><img src="<?php echo $this->getUrl('pub/media/icons/').'bookmark.png' ?>" /></a>
    </div>
<?php } } ?>

<div class="share-medias mobileview"><a href="javascript:;" onclick="openmForm()" class="opensharem"><img src="<?php echo $this->getUrl('pub/media/productpage/').'social-media.png' ?>" /><span><?php echo __('Share') ?></span></a>
<div class="social-media-icons" id="socialmediam" style="display:none">
    <span class="btn cancel" onclick="closemForm()"><img src="<?php echo $this->getUrl('pub/media/icons/').'close.png'; ?>"/></span>
    <!-- WhatsApp -->
    <?php /* <a target="_blank" href="https://api.whatsapp.com/send?text=<?php echo urlencode($_product->getProductUrl());?>">
            WhatsApp</a> */ ?>
    <div class="icons-s">        
        <!-- Facebook -->
        <a href="https://www.facebook.com/sharer/sharer.php?u=<?php echo urlencode($_product->getProductUrl());?>&t=<?php echo urlencode($_product->getName())?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on facebook">
            <img src="<?php echo $this->getUrl('pub/media/productpage/').'facebook-d.png'; ?>" alt="Facebook">
        </a>
        <!-- TWITTER -->
        <a href="http://twitter.com/home/?status=<?php echo urlencode($_product->getProductUrl());?>(<?php echo urlencode($_product->getName())?>)" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on Twitter">
            <img src="<?php echo $this->getUrl('pub/media/productpage/').'twitter-d.png'; ?>" alt="Twitter">
        </a>
        <!-- Pinterest -->
        <a href="https://pinterest.com/pin/create/button/?url=<?php echo urlencode($_product->getProductUrl()); ?>&media=<?php echo urlencode($_product->getImageUrl());?> &description=<?php echo urlencode($_product->getName()); ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Pin it">
            <img src="<?php echo $this->getUrl('pub/media/productpage/').'pinterest.png'; ?>" alt="Pinterest">
        </a>
        <!-- Google Plus -->
        <a href="https://plus.google.com/share?url=<?php echo urlencode($_product->getProductUrl()); ?>" onclick='javascript:window.open(this.href,"","width=640,height=480,left=0,top=0,location=no,status=yes,scrollbars=yes,resizable=yes");return false' title="Share on Google Plus">
            <img src="<?php echo $this->getUrl('pub/media/productpage/').'google-plus.png'; ?>" alt="Google Plus">
        </a>
    </div>
</div>
</div>


<script>
    
    function openmForm() {
        console.log('test');
      document.getElementById("socialmediam").style.display = "block";   
    }
    function closemForm() {
        console.log('test11');
      document.getElementById("socialmediam").style.display = "none";
    }    
  
</script>